//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Moriah.Arezzo.GuitarGame.Services {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SequenciaPremiacaoDTO", Namespace="http://schemas.datacontract.org/2004/07/Pepsi.Sorter.Web")]
    public partial class SequenciaPremiacaoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<int> OrdemField;
        
        private System.Collections.ObjectModel.ObservableCollection<bool> PremiacaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<int> Ordem {
            get {
                return this.OrdemField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdemField, value) != true)) {
                    this.OrdemField = value;
                    this.RaisePropertyChanged("Ordem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<bool> Premiacao {
            get {
                return this.PremiacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PremiacaoField, value) != true)) {
                    this.PremiacaoField = value;
                    this.RaisePropertyChanged("Premiacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PremioDTO", Namespace="http://schemas.datacontract.org/2004/07/Pepsi.Sorter.Web")]
    public partial class PremioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDPremiacaoField;
        
        private int IDPremioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPremiacao {
            get {
                return this.IDPremiacaoField;
            }
            set {
                if ((this.IDPremiacaoField.Equals(value) != true)) {
                    this.IDPremiacaoField = value;
                    this.RaisePropertyChanged("IDPremiacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPremio {
            get {
                return this.IDPremioField;
            }
            set {
                if ((this.IDPremioField.Equals(value) != true)) {
                    this.IDPremioField = value;
                    this.RaisePropertyChanged("IDPremio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Pepsi.Sorter.Service", ConfigurationName="Services.PremiacaoService")]
    public interface PremiacaoService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Pepsi.Sorter.Service/PremiacaoService/GetSequenciaPremiacao", ReplyAction="Pepsi.Sorter.Service/PremiacaoService/GetSequenciaPremiacaoResponse")]
        System.IAsyncResult BeginGetSequenciaPremiacao(System.AsyncCallback callback, object asyncState);
        
        Moriah.Arezzo.GuitarGame.Services.SequenciaPremiacaoDTO EndGetSequenciaPremiacao(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Pepsi.Sorter.Service/PremiacaoService/GetPremio", ReplyAction="Pepsi.Sorter.Service/PremiacaoService/GetPremioResponse")]
        System.IAsyncResult BeginGetPremio(int Tela, string evento, System.AsyncCallback callback, object asyncState);
        
        Moriah.Arezzo.GuitarGame.Services.PremioDTO EndGetPremio(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Pepsi.Sorter.Service/PremiacaoService/MarcaJogada", ReplyAction="Pepsi.Sorter.Service/PremiacaoService/MarcaJogadaResponse")]
        System.IAsyncResult BeginMarcaJogada(int Ordem, int Tela, string evento, System.AsyncCallback callback, object asyncState);
        
        void EndMarcaJogada(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Pepsi.Sorter.Service/PremiacaoService/CarimbaPremiacao", ReplyAction="Pepsi.Sorter.Service/PremiacaoService/CarimbaPremiacaoResponse")]
        System.IAsyncResult BeginCarimbaPremiacao(int IDPremiacao, int OrdemDaJogada, System.AsyncCallback callback, object asyncState);
        
        void EndCarimbaPremiacao(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PremiacaoServiceChannel : Moriah.Arezzo.GuitarGame.Services.PremiacaoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSequenciaPremiacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSequenciaPremiacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Moriah.Arezzo.GuitarGame.Services.SequenciaPremiacaoDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Moriah.Arezzo.GuitarGame.Services.SequenciaPremiacaoDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPremioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPremioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Moriah.Arezzo.GuitarGame.Services.PremioDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Moriah.Arezzo.GuitarGame.Services.PremioDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PremiacaoServiceClient : System.ServiceModel.ClientBase<Moriah.Arezzo.GuitarGame.Services.PremiacaoService>, Moriah.Arezzo.GuitarGame.Services.PremiacaoService {
        
        private BeginOperationDelegate onBeginGetSequenciaPremiacaoDelegate;
        
        private EndOperationDelegate onEndGetSequenciaPremiacaoDelegate;
        
        private System.Threading.SendOrPostCallback onGetSequenciaPremiacaoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPremioDelegate;
        
        private EndOperationDelegate onEndGetPremioDelegate;
        
        private System.Threading.SendOrPostCallback onGetPremioCompletedDelegate;
        
        private BeginOperationDelegate onBeginMarcaJogadaDelegate;
        
        private EndOperationDelegate onEndMarcaJogadaDelegate;
        
        private System.Threading.SendOrPostCallback onMarcaJogadaCompletedDelegate;
        
        private BeginOperationDelegate onBeginCarimbaPremiacaoDelegate;
        
        private EndOperationDelegate onEndCarimbaPremiacaoDelegate;
        
        private System.Threading.SendOrPostCallback onCarimbaPremiacaoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PremiacaoServiceClient() {
        }
        
        public PremiacaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PremiacaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PremiacaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PremiacaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetSequenciaPremiacaoCompletedEventArgs> GetSequenciaPremiacaoCompleted;
        
        public event System.EventHandler<GetPremioCompletedEventArgs> GetPremioCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> MarcaJogadaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CarimbaPremiacaoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Moriah.Arezzo.GuitarGame.Services.PremiacaoService.BeginGetSequenciaPremiacao(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSequenciaPremiacao(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moriah.Arezzo.GuitarGame.Services.SequenciaPremiacaoDTO Moriah.Arezzo.GuitarGame.Services.PremiacaoService.EndGetSequenciaPremiacao(System.IAsyncResult result) {
            return base.Channel.EndGetSequenciaPremiacao(result);
        }
        
        private System.IAsyncResult OnBeginGetSequenciaPremiacao(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Moriah.Arezzo.GuitarGame.Services.PremiacaoService)(this)).BeginGetSequenciaPremiacao(callback, asyncState);
        }
        
        private object[] OnEndGetSequenciaPremiacao(System.IAsyncResult result) {
            Moriah.Arezzo.GuitarGame.Services.SequenciaPremiacaoDTO retVal = ((Moriah.Arezzo.GuitarGame.Services.PremiacaoService)(this)).EndGetSequenciaPremiacao(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSequenciaPremiacaoCompleted(object state) {
            if ((this.GetSequenciaPremiacaoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSequenciaPremiacaoCompleted(this, new GetSequenciaPremiacaoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSequenciaPremiacaoAsync() {
            this.GetSequenciaPremiacaoAsync(null);
        }
        
        public void GetSequenciaPremiacaoAsync(object userState) {
            if ((this.onBeginGetSequenciaPremiacaoDelegate == null)) {
                this.onBeginGetSequenciaPremiacaoDelegate = new BeginOperationDelegate(this.OnBeginGetSequenciaPremiacao);
            }
            if ((this.onEndGetSequenciaPremiacaoDelegate == null)) {
                this.onEndGetSequenciaPremiacaoDelegate = new EndOperationDelegate(this.OnEndGetSequenciaPremiacao);
            }
            if ((this.onGetSequenciaPremiacaoCompletedDelegate == null)) {
                this.onGetSequenciaPremiacaoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSequenciaPremiacaoCompleted);
            }
            base.InvokeAsync(this.onBeginGetSequenciaPremiacaoDelegate, null, this.onEndGetSequenciaPremiacaoDelegate, this.onGetSequenciaPremiacaoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Moriah.Arezzo.GuitarGame.Services.PremiacaoService.BeginGetPremio(int Tela, string evento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPremio(Tela, evento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moriah.Arezzo.GuitarGame.Services.PremioDTO Moriah.Arezzo.GuitarGame.Services.PremiacaoService.EndGetPremio(System.IAsyncResult result) {
            return base.Channel.EndGetPremio(result);
        }
        
        private System.IAsyncResult OnBeginGetPremio(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Tela = ((int)(inValues[0]));
            string evento = ((string)(inValues[1]));
            return ((Moriah.Arezzo.GuitarGame.Services.PremiacaoService)(this)).BeginGetPremio(Tela, evento, callback, asyncState);
        }
        
        private object[] OnEndGetPremio(System.IAsyncResult result) {
            Moriah.Arezzo.GuitarGame.Services.PremioDTO retVal = ((Moriah.Arezzo.GuitarGame.Services.PremiacaoService)(this)).EndGetPremio(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPremioCompleted(object state) {
            if ((this.GetPremioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPremioCompleted(this, new GetPremioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPremioAsync(int Tela, string evento) {
            this.GetPremioAsync(Tela, evento, null);
        }
        
        public void GetPremioAsync(int Tela, string evento, object userState) {
            if ((this.onBeginGetPremioDelegate == null)) {
                this.onBeginGetPremioDelegate = new BeginOperationDelegate(this.OnBeginGetPremio);
            }
            if ((this.onEndGetPremioDelegate == null)) {
                this.onEndGetPremioDelegate = new EndOperationDelegate(this.OnEndGetPremio);
            }
            if ((this.onGetPremioCompletedDelegate == null)) {
                this.onGetPremioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPremioCompleted);
            }
            base.InvokeAsync(this.onBeginGetPremioDelegate, new object[] {
                        Tela,
                        evento}, this.onEndGetPremioDelegate, this.onGetPremioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Moriah.Arezzo.GuitarGame.Services.PremiacaoService.BeginMarcaJogada(int Ordem, int Tela, string evento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMarcaJogada(Ordem, Tela, evento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Moriah.Arezzo.GuitarGame.Services.PremiacaoService.EndMarcaJogada(System.IAsyncResult result) {
            base.Channel.EndMarcaJogada(result);
        }
        
        private System.IAsyncResult OnBeginMarcaJogada(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Ordem = ((int)(inValues[0]));
            int Tela = ((int)(inValues[1]));
            string evento = ((string)(inValues[2]));
            return ((Moriah.Arezzo.GuitarGame.Services.PremiacaoService)(this)).BeginMarcaJogada(Ordem, Tela, evento, callback, asyncState);
        }
        
        private object[] OnEndMarcaJogada(System.IAsyncResult result) {
            ((Moriah.Arezzo.GuitarGame.Services.PremiacaoService)(this)).EndMarcaJogada(result);
            return null;
        }
        
        private void OnMarcaJogadaCompleted(object state) {
            if ((this.MarcaJogadaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MarcaJogadaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MarcaJogadaAsync(int Ordem, int Tela, string evento) {
            this.MarcaJogadaAsync(Ordem, Tela, evento, null);
        }
        
        public void MarcaJogadaAsync(int Ordem, int Tela, string evento, object userState) {
            if ((this.onBeginMarcaJogadaDelegate == null)) {
                this.onBeginMarcaJogadaDelegate = new BeginOperationDelegate(this.OnBeginMarcaJogada);
            }
            if ((this.onEndMarcaJogadaDelegate == null)) {
                this.onEndMarcaJogadaDelegate = new EndOperationDelegate(this.OnEndMarcaJogada);
            }
            if ((this.onMarcaJogadaCompletedDelegate == null)) {
                this.onMarcaJogadaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMarcaJogadaCompleted);
            }
            base.InvokeAsync(this.onBeginMarcaJogadaDelegate, new object[] {
                        Ordem,
                        Tela,
                        evento}, this.onEndMarcaJogadaDelegate, this.onMarcaJogadaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Moriah.Arezzo.GuitarGame.Services.PremiacaoService.BeginCarimbaPremiacao(int IDPremiacao, int OrdemDaJogada, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCarimbaPremiacao(IDPremiacao, OrdemDaJogada, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Moriah.Arezzo.GuitarGame.Services.PremiacaoService.EndCarimbaPremiacao(System.IAsyncResult result) {
            base.Channel.EndCarimbaPremiacao(result);
        }
        
        private System.IAsyncResult OnBeginCarimbaPremiacao(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int IDPremiacao = ((int)(inValues[0]));
            int OrdemDaJogada = ((int)(inValues[1]));
            return ((Moriah.Arezzo.GuitarGame.Services.PremiacaoService)(this)).BeginCarimbaPremiacao(IDPremiacao, OrdemDaJogada, callback, asyncState);
        }
        
        private object[] OnEndCarimbaPremiacao(System.IAsyncResult result) {
            ((Moriah.Arezzo.GuitarGame.Services.PremiacaoService)(this)).EndCarimbaPremiacao(result);
            return null;
        }
        
        private void OnCarimbaPremiacaoCompleted(object state) {
            if ((this.CarimbaPremiacaoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CarimbaPremiacaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CarimbaPremiacaoAsync(int IDPremiacao, int OrdemDaJogada) {
            this.CarimbaPremiacaoAsync(IDPremiacao, OrdemDaJogada, null);
        }
        
        public void CarimbaPremiacaoAsync(int IDPremiacao, int OrdemDaJogada, object userState) {
            if ((this.onBeginCarimbaPremiacaoDelegate == null)) {
                this.onBeginCarimbaPremiacaoDelegate = new BeginOperationDelegate(this.OnBeginCarimbaPremiacao);
            }
            if ((this.onEndCarimbaPremiacaoDelegate == null)) {
                this.onEndCarimbaPremiacaoDelegate = new EndOperationDelegate(this.OnEndCarimbaPremiacao);
            }
            if ((this.onCarimbaPremiacaoCompletedDelegate == null)) {
                this.onCarimbaPremiacaoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCarimbaPremiacaoCompleted);
            }
            base.InvokeAsync(this.onBeginCarimbaPremiacaoDelegate, new object[] {
                        IDPremiacao,
                        OrdemDaJogada}, this.onEndCarimbaPremiacaoDelegate, this.onCarimbaPremiacaoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Moriah.Arezzo.GuitarGame.Services.PremiacaoService CreateChannel() {
            return new PremiacaoServiceClientChannel(this);
        }
        
        private class PremiacaoServiceClientChannel : ChannelBase<Moriah.Arezzo.GuitarGame.Services.PremiacaoService>, Moriah.Arezzo.GuitarGame.Services.PremiacaoService {
            
            public PremiacaoServiceClientChannel(System.ServiceModel.ClientBase<Moriah.Arezzo.GuitarGame.Services.PremiacaoService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetSequenciaPremiacao(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetSequenciaPremiacao", _args, callback, asyncState);
                return _result;
            }
            
            public Moriah.Arezzo.GuitarGame.Services.SequenciaPremiacaoDTO EndGetSequenciaPremiacao(System.IAsyncResult result) {
                object[] _args = new object[0];
                Moriah.Arezzo.GuitarGame.Services.SequenciaPremiacaoDTO _result = ((Moriah.Arezzo.GuitarGame.Services.SequenciaPremiacaoDTO)(base.EndInvoke("GetSequenciaPremiacao", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPremio(int Tela, string evento, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = Tela;
                _args[1] = evento;
                System.IAsyncResult _result = base.BeginInvoke("GetPremio", _args, callback, asyncState);
                return _result;
            }
            
            public Moriah.Arezzo.GuitarGame.Services.PremioDTO EndGetPremio(System.IAsyncResult result) {
                object[] _args = new object[0];
                Moriah.Arezzo.GuitarGame.Services.PremioDTO _result = ((Moriah.Arezzo.GuitarGame.Services.PremioDTO)(base.EndInvoke("GetPremio", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginMarcaJogada(int Ordem, int Tela, string evento, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = Ordem;
                _args[1] = Tela;
                _args[2] = evento;
                System.IAsyncResult _result = base.BeginInvoke("MarcaJogada", _args, callback, asyncState);
                return _result;
            }
            
            public void EndMarcaJogada(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("MarcaJogada", _args, result);
            }
            
            public System.IAsyncResult BeginCarimbaPremiacao(int IDPremiacao, int OrdemDaJogada, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = IDPremiacao;
                _args[1] = OrdemDaJogada;
                System.IAsyncResult _result = base.BeginInvoke("CarimbaPremiacao", _args, callback, asyncState);
                return _result;
            }
            
            public void EndCarimbaPremiacao(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("CarimbaPremiacao", _args, result);
            }
        }
    }
}
